# Important python libraries

 - `numpy` (numerics) + `scipy` (scientific functions) 
 - `matplotlib` - plotting
 - `astropy` - convenient operations on data for Data Science  (`pandas` is another alternative) 
 - `scikit-learn` - machine learning
 
We'll meet them very soon during the ML session.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [2]:
import numpy

In [3]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [7]:
print x[:3]
print x[3:7]
print x[7:]

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-7-a1ee579a2a36>, line 1)

### Vector operations

In [ ]:
x = numpy.arange(10 ** 6)
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

In [ ]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

In [ ]:
Z = numpy.arange(15).reshape(5, 3)
Z

In [ ]:
numpy.log(numpy.exp(Z)) # type conversion happened

In [ ]:
Z += 4

In [ ]:
Z

In [ ]:
Z[::2, :]

In [ ]:
Z[[0, 2, 4], :]

In [ ]:
Z.sum(axis=1)

In [ ]:
# axes are also zero-numerated
Z.sum(axis=0)

In [ ]:
Z.max(axis=1)

In [ ]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

## Indexing with boolean array

In [ ]:
x = numpy.arange(10)
x

In [ ]:
x > 3

In [ ]:
x[x < 7.4]

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [ ]:
x = numpy.arange(10)
y = x[:5]

print x, y
y[0] = 10
print x, y

this happened because x and y point __to the same place in memory__

In [ ]:
x = numpy.arange(10)
y = x[:5].copy()
print x, y
y[0] = 10
print x, y

## Random numbers

module `numpy.random` helps with generating random numbers

In [ ]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

## Sorting

In [ ]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [ ]:
print x[:10]
print x[-10:]

## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [ ]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers)

In [ ]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers))

In [ ]:
indices[:10]

In [ ]:
random_numbers.min(), random_numbers.max()

In [ ]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

In [ ]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

## Exercise

In [ ]:
import numpy as np


In [ ]:
np.random.normal(loc=0.1, scale=1.2, size=10000)

In [9]:
random_numbers = np.random.normal(loc=0.1, scale=1.2, size=10000)

print(random_numbers[random_numbers>0])

[ 0.89065673  0.65194391  0.68863048 ...,  0.99534196  2.58629539
  0.17699025]


In [ ]:
# 3. count number of left numbers, their minimum, maximum, mean and variance.
s=0
num=np.array([])
random_numbers = np.random.normal(loc=0.1, scale=1.2, size=10000)
for i in random_numbers:
    if i <= 0:
        s += 1
        num = np.append(num, i)
        
print('count', s)
print('min', num.min())
print('max', num.max())
print('mean', np.mean(num))
print('std', np.std(num))

## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
