# Important python libraries

 - `numpy` (numerics) + `scipy` (scientific functions) 
 - `matplotlib` - plotting
 - `astropy` - convenient operations on data for Data Science  (`pandas` is another alternative) 
 - `scikit-learn` - machine learning
 
We'll meet them very soon during the ML session.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [1]:
import numpy

In [2]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [6]:
print x[:3]
print x[3:7]
print x[7:]

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector operations

In [7]:
x = numpy.arange(10 ** 6)
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

array([  1.20000000e+01,   1.50000000e+01,   1.80000000e+01, ...,
         3.00000300e+06,   3.00000600e+06,   3.00000900e+06])

In [8]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

100 loops, best of 3: 6.26 ms per loop


In [9]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

In [11]:
Z += 4

In [12]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [13]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [14]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [15]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [16]:
# axes are also zero-numerated
Z.sum(axis=0)

array([50, 55, 60])

In [17]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [18]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Indexing with boolean array

In [19]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [21]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [22]:
x = numpy.arange(10)
y = x[:5]

print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


this happened because x and y point __to the same place in memory__

In [23]:
x = numpy.arange(10)
y = x[:5].copy()
print x, y
y[0] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random numbers

module `numpy.random` helps with generating random numbers

In [24]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

array([ 11.78220635,   8.93663103, -17.50627085, ...,  17.10257018,
         7.24243523,  -0.95099759])

## Sorting

In [25]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [26]:
print x[:10]
print x[-10:]

[ 0.00021619  0.00066141  0.0022386   0.00231872  0.00866861  0.00889664
  0.01014405  0.01216177  0.01273415  0.01466487]
[ 0.99120831  0.99250643  0.99419286  0.99490179  0.99550734  0.99653262
  0.99681669  0.99848937  0.99872478  0.99887051]


## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [27]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers)

In [28]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers))

True

In [29]:
indices[:10]

array([794,   2, 719, 257, 385, 486, 763, 772, 554, 559])

In [30]:
random_numbers.min(), random_numbers.max()

(0.0004961517756608691, 0.99889210024516806)

In [31]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(219, 0.99889210024516806)

In [32]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(794, 0.0004961517756608691)

## Exercise

In [1]:
import numpy as np


In [2]:
np.random.normal(loc=0.1, scale=1.2, size=10000)

array([ 0.1362757 ,  0.03710384,  0.2878032 , ...,  0.11957981,
       -0.85250577, -1.8029315 ])

In [5]:
positive = []
random_numbers = np.random.normal(loc=0.1, scale=1.2, size=10000)
for i in random_numbers:
    if i > 0:
        positive.append(i)
print(positive)

[0.60741264446159071, 1.660668069500322, 0.37231467872811519, 0.88158496044985935, 0.92983501253908929, 1.161700663985348, 1.2874071186529403, 0.24763168537627128, 0.55611312704680615, 2.6551344150887721, 1.1957209699080753, 0.20271125232132969, 0.057284610736273597, 2.0830814350737787, 0.68522185624415466, 1.4195613491921022, 0.65227105944098451, 0.33061823821636876, 1.675717873215159, 1.0908470189061255, 0.95249705477820079, 1.4032421655555629, 0.82122214656280135, 0.53653058424057332, 0.90431464173553655, 1.5705630286555936, 1.9899074624285853, 2.6644529869972073, 0.23701614360218276, 0.90128732945387569, 0.1555366765725954, 0.81146045285371604, 0.054619268890114425, 0.24013777318600679, 0.017981566571860452, 2.232388735904637, 0.8386086462632073, 1.4960496943119435, 0.77993058446287011, 2.0357218132227968, 0.26408667534384622, 0.23687868166132212, 1.7692354093099403, 1.7150750589455546, 0.45039173657327747, 1.4553153630518878, 0.91190217315069344, 2.1019631100763214, 0.263059242487

In [4]:
# 3. count number of left numbers, their minimum, maximum, mean and variance.
s=0
num=np.array([])
random_numbers = np.random.normal(loc=0.1, scale=1.2, size=10000)
for i in random_numbers:
    if i <= 0:
        s += 1
        num = np.append(num, i)
        
print('count', s)
print('min', num.min())
print('max', num.max())
print('mean', np.mean(num))
print('std', np.std(num))

count 4653
min -4.6203628175
max -7.82453507879e-05
mean -0.927115974626
std 0.700411526212


## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
